server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    url: jdbc:mariadb://localhost:3306/PRODUCT_SALE?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
